### ISSUE TITLE
pnpm 依赖安装失败

### ISSUE THREAD

**Issue by srarlight** [Kele-Bingtang/kbt-vue3-admin#4]
![image](https://github.com/user-attachments/assets/0b943b88-f33f-484e-bbc2-840f08d2b69b)
pnpm install 重试了好多次还是不行 请问要怎么安装

**Comment by Kele-Bingtang** [comment]
看起来是网络的问题，你 pnpm 仓库源是多少

**Comment by srarlight** [comment]
> 看起来是网络的问题，你 pnpm 仓库源是多少

https://registry.npmmirror.com  我是有梯子的。其他项目我试了都是可以安装的。就是你这个起不来呢

**Comment by Kele-Bingtang** [comment]
把 `pnpm-lock.yaml` 去掉试试
